### ISSUE TITLE
i bottoni che gestiscono la quantità di ingredienti da aggiungere al carrello nel negozio non funzionano nel modo corretto

### ISSUE THREAD

**Issue by AlessandroCarella** [zSavT/Healthy-Catering#190]

**Comment by zSavT** [comment]
@AlessandroCarella cosa non va comunque?

**Comment by AlessandroCarella** [comment]
> @AlessandroCarella cosa non va comunque?

Gi fixato nella pull del refactoring

**Comment by zSavT** [comment]
> > @AlessandroCarella cosa non va comunque?
> 
> Gi fixato nella pull del refactoring

Ok, ma cosa non andava?

**Comment by zSavT** [comment]
@AlessandroCarella

**Comment by AlessandroCarella** [comment]
> > > @AlessandroCarella cosa non va comunque?
> > 
> > Gi fixato nella pull del refactoring
> 
> Ok, ma cosa non andava?

Se premevi il - a ripetizione poi non saliva piu il counter
