### ISSUE TITLE
Il ricettario non funziona prima di parlare con lo zio nel tutorial

### ISSUE THREAD

**Issue by AlessandroCarella** [zSavT/Healthy-Catering#191]
Se si entra nel tutorial ma non si va direttamente a parlare con lo zio ma si preme R il ricettario si apre ma nessuno dei bottoni funziona

**Comment by zSavT** [comment]
> Se si entra nel tutorial ma non si va direttamente a parlare con lo zio ma si preme R il ricettario si apre ma nessuno dei bottoni funziona

Le strade da poter percorrere per il fix sono due:

- Non si permette al giocatore di aprire il ricettario prima della parte del tutorial dedicata al ricettario.
- Si corregge questo problema.

Per quanto la prima è più semplice e sbrigativa da implementare ed ha un costo bassissimo, direi di fare la seconda, in virtù del fatto che devi ri-scrivere\modificare alcuni classi perchè non sono ottimale, a sto punto si fanno due piccioni con una fava.

**Comment by zSavT** [comment]
> > > Se si entra nel tutorial ma non si va direttamente a parlare con lo zio ma si preme R il ricettario si apre ma nessuno dei bottoni funziona
> > 
> > Le strade da poter percorrere per il fix sono due:
> > 
> > - Non si permette al giocatore di aprire il ricettario prima della parte del tutorial dedicata al ricettario.
> > - Si corregge questo problema.
> > 
> > Per quanto la prima è più semplice e sbrigativa da implementare ed ha un costo bassissimo, direi di fare la seconda, in virtù del fatto che devi ri-scrivere\modificare alcuni classi perchè non sono ottimale, a sto punto si fanno due piccioni con una fava.
> > 
> > @AlessandroCarella ti taggo perchè non so se hai ri-attivato le notifiche.
> 
> Le strade possibili sono ovvie e anche con la seconda che hai detto non ci dovrebbe volere niente
> Per favore smettila di farmi da tutor/capo, il tuo contributo è piu che apprezzato nel momento in cui sto avendo difficolta e vengo espressamente a chiederti aiuto e/o quando un probroblema è veramente grande (es. il magazzino), grazie
> 
> P.S.: non ho riattivato le notifiche via mail quindi si, taggami ma non abusarne, sopratutto sull'unica pull request attiva ora tanto quando mi metto a lavorare vado sempre a vedere la conversazione oltre a fare il pull

Non sono ovvie, ci possono anche essere altre che non vengono in mente a me ed a te si, in più sia io che tu dobbiamo essere sempre informati su quello che si fa.

**Comment by zSavT** [comment]
Testato con il nuovo main dopo il refactoring e funziona tutto.
