### ISSUE TITLE
Anche l'interazione con i passanti non funziona con le stesse condizioni del ricettario

### ISSUE THREAD

**Issue by AlessandroCarella** [zSavT/Healthy-Catering#195]

**Comment by zSavT** [comment]
@AlessandroCarella anche qui non ho capito bene.

**Comment by AlessandroCarella** [comment]
> @AlessandroCarella anche qui non ho capito bene.

Come il ricettario che non funziona prima di aver servito il primo cliente (o un'altra condizione che ora non ricordo) non si puo andare avanti nei dialoghi se non si soddisfa quella condizione
Penso sia qualcosa dovuta o ai tuoi reset o alla classe che gestisce il tutorial

**Comment by zSavT** [comment]
> > @AlessandroCarella anche qui non ho capito bene.
> 
> Come il ricettario che non funziona prima di aver servito il primo cliente (o un'altra condizione che ora non ricordo) non si puo andare avanti nei dialoghi se non si soddisfa quella condizione
> Penso sia qualcosa dovuta o ai tuoi reset o alla classe che gestisce il tutorial

Quali reset?

**Comment by AlessandroCarella** [comment]
> > > @AlessandroCarella anche qui non ho capito bene.
> > 
> > Come il ricettario che non funziona prima di aver servito il primo cliente (o un'altra condizione che ora non ricordo) non si puo andare avanti nei dialoghi se non si soddisfa quella condizione
> > Penso sia qualcosa dovuta o ai tuoi reset o alla classe che gestisce il tutorial
> 
> Quali reset?

No idea

**Comment by zSavT** [comment]
> > > > @AlessandroCarella anche qui non ho capito bene.
> > > 
> > > Come il ricettario che non funziona prima di aver servito il primo cliente (o un'altra condizione che ora non ricordo) non si puo andare avanti nei dialoghi se non si soddisfa quella condizione
> > > Penso sia qualcosa dovuta o ai tuoi reset o alla classe che gestisce il tutorial
> > 
> > Quali reset?
> 
> No idea

Sarà sicuramente dovuto alle modifiche che hai fatto durante il refactoring. Io da ieri mi son messo a lavorare ed questo problema esisteva già a quanto pare. Quindi devi rivedere lì.

**Comment by zSavT** [comment]
Testato con il nuovo main dopo il refactoring e funziona tutto.
