### ISSUE TITLE
il waypoint non viene nascosto quando si fanno acquisti

### ISSUE THREAD

**Issue by AlessandroCarella** [zSavT/Healthy-Catering#196]

**Comment by zSavT** [comment]
Screen
Ricordo o di averlo nascosto o che l'ho lasciato perché non era visibile perché coperto.

**Comment by AlessandroCarella** [comment]
> Screen
> Ricordo o di averlo nascosto o che l'ho lasciato perché non era visibile perché coperto.

eee anche a me di solito non appare ma "ho vissuto" un caso limite e mi sono scordato di fare lo screen

può essere anche che io abbia rotto qualcosa che ora lo fa apparire, non ti preoccupare poi risolvo io
