### ISSUE TITLE
Ridimensionamento testo menu aiuto

### ISSUE THREAD

**Issue by AlessandroCarella** [zSavT/Healthy-Catering#197]
ho aperto il menu aiuto per testare e stavo pensando che potremmo fare delle modifiche
la visualizzazione al momento è cosi:
![image](https://user-images.githubusercontent.com/79840231/192150771-8d2c490d-d8c0-430d-a1d4-5e3b6677e984.png)

io propongo di abbassare le frecce più in basso, cosi che il lato più in alto delle frecce coincida con il lato più in alto della gif cosi da poter allargare il testo

questo ci fa anche mantenere una costanza nell'ui con i testi del tutorial:
![image](https://user-images.githubusercontent.com/79840231/192150864-97b15b3a-4825-442e-b30e-d5fa421cae7d.png)
poi avremo quindi una vista cosi (scusa se è stilizzata ma vado un po di corsa)
![Uploading image.png…]()

**Comment by zSavT** [comment]
Ci occupiamo dei bug ora, non di ripensare l'interfaccia ed altro.

**Comment by AlessandroCarella** [comment]
> Ci occupiamo dei bug ora, non di ripensare l'interfaccia ed altro.

ripeto, sto solo annotando le idee per il futuro, non mi sto mettendo a fare queste cose ora
la PR aperta al momento è per il refactoring e non ha neanche senso pushare questo tipo di modifiche
